### ISSUE TITLE
app/v1beta2 deprecated since kubernetes 1.16

### ISSUE THREAD

**Issue by dchaumond** [latchmihay/kube-prometheus-pushgateway#4]
Hi, nice additional repo for prometheus.

Trying to install it, it's not working for recent kubernetes version as it is using deployment deprecated apps/v1beta2. I think this can be updated to apps/v1 with no trouble.

https://github.com/latchmihay/kube-prometheus-pushgateway/blob/master/prometheus-pushgateway/pushgateway.libsonnet#L26

**Comment by dchaumond** [comment]
Sorry, apps/v1beta2 and apps/v1

**Comment by latchmihay** [comment]
you are right, thank you.
