### ISSUE TITLE
Latest kube prometheus

### ISSUE THREAD

**Issue by thyn** [latchmihay/kube-prometheus-pushgateway#6]
docker run --rm -v $(pwd):$(pwd) --workdir $(pwd) quay.io/coreos/jsonnet-ci jb install github.com/latchmihay/kube-prometheus-pushgateway/prometheus-pushgateway
jb: error: invalid character 'l' looking for beginning of value

**Comment by latchmihay** [comment]
That command is meant to be ran inside the `coreos/kube-prometheus` repo (after you clone it)

Check out the example here: https://github.com/latchmihay/kube-prometheus-pushgateway#usage-along-side-kube-prometheus-in-a-container

If thats not the case, my next best guess is that your `jsonnetfile.json` is malformed

**Comment by thyn** [comment]
yes, jsonnetfile.json was malformed.
